<a href="https://colab.research.google.com/github/Sardaar2003/Projects/blob/main/Numpy_Practice_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**List to NP Array**

In [7]:
lst=[1,2,3,4]
np_list=np.array(lst,ndmin=2)
np_list

array([[1, 2, 3, 4]])

In [3]:
type(np_list)

numpy.ndarray

**Arange Function**

In [6]:
arr2=np.arange(10,145,8)

array([ 10,  18,  26,  34,  42,  50,  58,  66,  74,  82,  90,  98, 106,
       114, 122, 130, 138])

**MultiDimensional Array**

In [8]:
a=[[1,2,3],[4,5,7],[75,23,12]]
arr2=np.array(a)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  7],
       [75, 23, 12]])

**Size of a np array**

In [11]:
print("total number of element : ",arr2.size)
print("Number of rows : ",np.size(arr2,axis=0))
print("Number of Columns : ",np.size(arr2,axis=1))

total number of element :  9
Number of rows :  3
Number of Columns :  3


**Shape Function**

In [16]:
# a=[[1,2,3],[4,5,7],[75,23,12]]
print(np.size(arr2,0),np.size(arr2,1))
print(arr2.shape)

3 3
(3, 3)


**Data type**

In [18]:
print(arr2.dtype)

int64


**Ndim Function**

In [20]:
arr3=np.array([[1,2,3,4],[5,7,7,3],[34,23,12,3]])
print(arr2.ndim)
print(arr3.ndim)

2
2


**Zeros Function**

In [27]:
arr4=np.zeros((4,6),dtype=float)
print(arr4.ndim)
print(arr4.shape)
print(arr4)

2
(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


**Ones Function**

In [28]:
arr5=np.ones((5,23),dtype=int)
print(arr5.ndim)
print(arr5.shape)
print(arr5)

2
(5, 23)
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


**Eye Function**

In [33]:
arr6=np.eye(100000)
print(arr6)
print(arr6.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(100000, 100000)


**Empty Function**

In [36]:
arr7=np.empty(shape=(2,4),dtype=int)
print(arr7)

[[96555877942751              0              0              0]
 [             0              0              0              0]]


**Random Function**

**np.random.rand**

In [40]:
arr7=np.random.rand(3,4)
print(arr7)

[[0.21645911 0.51804988 0.79964717 0.09172694]
 [0.83207039 0.40656255 0.58539813 0.96955759]
 [0.83014915 0.79035175 0.39693976 0.68418002]]


In [41]:
arr8=np.random.randint(13,32,10)
print(arr8)

[15 26 29 13 30 18 27 26 21 18]


In [42]:
arr9=np.random.randn(100)
print(arr9)

[ 0.20392694  0.19242221  0.52022016  0.38033503  2.11605034 -1.11916252
 -0.56970714 -0.56564904 -0.19350257 -0.07894384 -0.15616054  0.94000724
  0.56452238  0.42668509 -0.16957401  2.43093151  0.91154076  1.58700956
  1.85566036  1.69886343 -0.85074396  1.98683831  0.63755275 -2.71515782
  0.86600511 -0.77244394  1.57969592 -0.55402372  0.4715846   0.75974586
 -0.8729555   0.01982933 -0.01325864  0.2963031  -0.10534206  0.70126299
 -1.28540155  0.28543953 -1.23157591  0.29005289  0.41786588  0.36623736
  0.05273156 -0.77413102 -2.15605628 -1.24911727  0.23499571 -1.74344445
 -0.9534968   0.8370367   0.57428593  1.69237619  0.26557438  0.71260945
 -0.43537455  1.07446934 -1.19016609  0.81685722  0.38011044  0.59506363
 -0.29865866 -0.54472156 -1.10252975 -1.46563247  1.65809684 -0.41842006
  0.05363601  0.29544982  0.82921392 -0.38074602 -0.19874192  2.06136527
 -0.87974922  1.55823494 -0.32314675  0.80757131 -0.24999714 -1.79924835
  0.35467366  0.16582205  0.922643   -0.97011085  0

**Reshape Function**

In [48]:
print(arr9.reshape((25,4)))
arr10=np.random.randint(1,100,(2,4))
print(arr10)

[[ 0.20392694  0.19242221  0.52022016  0.38033503]
 [ 2.11605034 -1.11916252 -0.56970714 -0.56564904]
 [-0.19350257 -0.07894384 -0.15616054  0.94000724]
 [ 0.56452238  0.42668509 -0.16957401  2.43093151]
 [ 0.91154076  1.58700956  1.85566036  1.69886343]
 [-0.85074396  1.98683831  0.63755275 -2.71515782]
 [ 0.86600511 -0.77244394  1.57969592 -0.55402372]
 [ 0.4715846   0.75974586 -0.8729555   0.01982933]
 [-0.01325864  0.2963031  -0.10534206  0.70126299]
 [-1.28540155  0.28543953 -1.23157591  0.29005289]
 [ 0.41786588  0.36623736  0.05273156 -0.77413102]
 [-2.15605628 -1.24911727  0.23499571 -1.74344445]
 [-0.9534968   0.8370367   0.57428593  1.69237619]
 [ 0.26557438  0.71260945 -0.43537455  1.07446934]
 [-1.19016609  0.81685722  0.38011044  0.59506363]
 [-0.29865866 -0.54472156 -1.10252975 -1.46563247]
 [ 1.65809684 -0.41842006  0.05363601  0.29544982]
 [ 0.82921392 -0.38074602 -0.19874192  2.06136527]
 [-0.87974922  1.55823494 -0.32314675  0.80757131]
 [-0.24999714 -1.79924835  0.35

**Linspace Function**

In [49]:
arr1=np.linspace(1,10,100)
print(arr1)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

**Flatten Function**

In [52]:
arr12=np.random.randint(1,17,(2,5))
print(arr12)
print(arr12.shape)
arr12=arr12.flatten()
print(arr12)
print(arr12.shape)


[[15  2 15  4 16]
 [ 7 15 16 13  7]]
(2, 5)
[15  2 15  4 16  7 15 16 13  7]
(10,)


**Logspace Function**

In [56]:
np.logspace(1,10,100,base=5)

array([5.00000000e+00, 5.78778956e+00, 6.69970160e+00, 7.75529259e+00,
       8.97720029e+00, 1.03916292e+01, 1.20289126e+01, 1.39241630e+01,
       1.61180250e+01, 1.86575474e+01, 2.15971916e+01, 2.50000000e+01,
       2.89389478e+01, 3.34985080e+01, 3.87764629e+01, 4.48860015e+01,
       5.19581461e+01, 6.01445631e+01, 6.96208149e+01, 8.05901251e+01,
       9.32877369e+01, 1.07985958e+02, 1.25000000e+02, 1.44694739e+02,
       1.67492540e+02, 1.93882315e+02, 2.24430007e+02, 2.59790731e+02,
       3.00722816e+02, 3.48104075e+02, 4.02950626e+02, 4.66438685e+02,
       5.39929790e+02, 6.25000000e+02, 7.23473695e+02, 8.37462699e+02,
       9.69411574e+02, 1.12215004e+03, 1.29895365e+03, 1.50361408e+03,
       1.74052037e+03, 2.01475313e+03, 2.33219342e+03, 2.69964895e+03,
       3.12500000e+03, 3.61736847e+03, 4.18731350e+03, 4.84705787e+03,
       5.61075018e+03, 6.49476827e+03, 7.51807039e+03, 8.70260186e+03,
       1.00737656e+04, 1.16609671e+04, 1.34982447e+04, 1.56250000e+04,
      

**Copy function**

In [61]:
arr13=np.random.randint(1,45,(4,6))
arr14=arr13
print(arr13,id(arr13))
print(arr14,id(arr14))
arr14=np.copy(arr13)
print(arr13,id(arr13))
print(arr14,id(arr14))

[[29  5  3 10 25 15]
 [29  5  8  6 24 23]
 [41 34  7  8 12 19]
 [27 43  6 13 12 35]] 139460932108816
[[29  5  3 10 25 15]
 [29  5  8  6 24 23]
 [41 34  7  8 12 19]
 [27 43  6 13 12 35]] 139460932108816
[[29  5  3 10 25 15]
 [29  5  8  6 24 23]
 [41 34  7  8 12 19]
 [27 43  6 13 12 35]] 139460932108816
[[29  5  3 10 25 15]
 [29  5  8  6 24 23]
 [41 34  7  8 12 19]
 [27 43  6 13 12 35]] 139460932007280


**Max,min,sum function**

In [68]:
arr15=np.random.randint(1,54,23)
arr16=np.random.randint(1,54,(34,2))
print("max  row : ",arr15.max(axis=0))
print("min row : ",arr15.min(axis=0))
print("sum row : ",arr15.sum(axis=0))

print("---------------------")
print("max row : ",arr16.max(axis=0))
print("min row : ",arr16.min(axis=0))
print("sum row : ",arr16.sum(axis=0))

print("-----------------------")
print("max col : ",arr16.max(axis=1))
print("min col : ",arr16.min(axis=1))
print("sum col : ",arr16.sum(axis=1))

max  row :  52
min row :  2
sum row :  614
---------------------
max row :  [53 52]
min row :  [1 1]
sum row :  [936 786]
-----------------------
max col :  [38 35 40 26 21 10 53 29 17 33 50 42 29 41 33 51 51 13 50 35  8 48 51 32
 40 32 52 38 39 20 38 35 34 50]
min col :  [20 19  1 12 13  1 30 12  9  3 11 37 23 20  3 15 18  2 17  5  1 10  2 13
 20 28  1 18 23 17 37 24 19 24]
sum col :  [58 54 41 38 34 11 83 41 26 36 61 79 52 61 36 66 69 15 67 40  9 58 53 45
 60 60 53 56 62 37 75 59 53 74]


**Seed Function**

In [75]:
arr17=np.random.seed(3)
arr18=np.random.randint(1,34,(32,12))
print(arr18)

[[25  4  9  1 22 20 11 11 22 33 21 30]
 [15 27 18 27 23  3  3  2 27  6 30 25]
 [ 8 16 21 31 22 15 29  1  1 19  8  2]
 [22 11 28 17 17 33 17 19 12 33 32 14]
 [31  3 29 27 11 28 22 30 33 10 25 12]
 [21 11 17 13  5 20 17  2  2 19  3 24]
 [21 18 23 29  8 33 29 17 28  9 21  9]
 [25 15 13 20 10 27  6 21 32 18 10 33]
 [14  8 29  9 27 25 21 31 18 33 23 32]
 [33 24 25 22 27 16 29 12 18  8 14 32]
 [ 5 31 14 14 33 25 22  7 24 29 13 29]
 [11 12 22 29  9 26 12 26 26  5 22 30]
 [ 1 31  8 22 30  8 31 31 13 12 22 31]
 [ 8 29 16 23 27 10 20  6 13 27 25 24]
 [19  1  8 27 33 15 20 27  4 22 24 13]
 [19 29  7  7 20 14  1 13  5 31 22  1]
 [14 22  5 30  6  7 28 33  2 32  8 33]
 [ 4 24 26 27 15 23 13 12 31 16  4  7]
 [15 12  6 23 16 17  2 19 30 22 27 13]
 [24 18 31  8 11 26 11  2 21 19 13  5]
 [ 4  5 22  9 20  2 19  6 28 12  4 11]
 [26 20 22  7 31 27 32  1 15 26 24 33]
 [21 19 11 26 32 28 13 12 25 27 25 27]
 [ 5 29  1 21 11  6 29 10 21 20 33 20]
 [ 5 12 32 22  9 26 33 13  2 21 12 21]
 [30 33 25  8 21  4 23 24

**Sorting Function**

In [85]:
# arr17=np.random.seed(3)
arr18=np.random.randint(1,34,(32,12))
print(arr18)
print('-'*555)
print(np.sort(arr18,axis=1,kind='mergesort'))
# print(arr18)
print('*'*555)
print(np.sort(arr18,axis=0,kind='mergesort'))
# print(arr18)
# print(arr18)

[[22 33 18 28  1 13 33 22 22  5 26 14]
 [29 31 13 17 28 17 21 30 21 12 11 15]
 [11 21  6 30 13 12 29  1  1 27  7  8]
 [18 25 23 22 12 15  7 12  3 16 30 24]
 [27  3 26  1  3 26 13 20 22 13 14  9]
 [12 32  2 21  4  6  9 31  6  4 14 19]
 [10  6  2 14  6  9 21 33  6 27 13  1]
 [10 19 33 18 27  9 29 14 26 31 32  2]
 [27 25  1  4  7  9  5 27  6 24 23 28]
 [ 6 22 14 29 32 30 22 20 32 27 22 23]
 [22 31 22 27  4 18 26 21  3 18  1 29]
 [27 27  6  1 18 31  5 17 23 16 17  8]
 [27 20 26 13 22 25 28 25 23  3 29 13]
 [10 18  9 33 24  5  3  4 19  8 31  5]
 [17  9 14 15 31 27 11  8 30 25 16 32]
 [ 2 17 33  4 24 26 20 21 15  8  2 11]
 [10  9 11 31 20 14 33 26 16 32 23 28]
 [ 4 22  3  3 14  3 11  7 23  8 29 15]
 [15 29  1 21  1 23  5 25 20  8 33 16]
 [33 30 13 30 13  3 19 17 28 15 13 14]
 [11 25 13 32 10 13 22 26 17 17 10  8]
 [23 31 22  4 30 26 26 11  8  9  6 33]
 [ 6 30  5 11 32 15  6  8  7 16 25 29]
 [ 8 15 20 31 25 22 28  4 20 22 26 17]
 [20 18 22 21 15 26  7 29 19 15 14 10]
 [29 15 31  7 18 22  5 21

In [87]:
print(np.sort(arr18.flatten(),kind='mergesort'))

[ 1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  3  3  3  3  3  3  3
  3  3  3  4  4  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5
  5  5  6  6  6  6  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7
  8  8  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9  9  9
  9 10 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 11
 11 11 11 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13 13 13 13 13 13 13
 13 13 13 13 14 14 14 14 14 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15
 15 15 15 15 15 16 16 16 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17
 17 17 17 18 18 18 18 18 18 18 18 18 18 19 19 19 19 19 19 19 19 20 20 20
 20 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 22 22 22 22 22
 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 23 23 23 23 23 23
 23 23 23 23 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 26 26
 26 26 26 26 26 26 26 26 26 26 26 26 26 27 27 27 27 27 27 27 27 27 27 27
 27 27 28 28 28 28 28 28 28 28 28 28 29 29 29 29 29

**Mathematical Operation**

In [94]:
np.random.seed(3)
arr1=np.random.randint(1,32,(10,4))
print(arr1)
print("---"*12)
print(arr1+34)
print("---"*12)
print(arr1-34)
print("---"*12)
print(arr1*2)
print("---"*12)
print(arr1/2)
print("---"*12)
print(arr1//4)
print("---"*12)
print(arr1%4)

[[11 25 26  4]
 [25  9  1 22]
 [30 20 11 12]
 [26 10 11 22]
 [24  7  1 21]
 [13 30  8 15]
 [25 27 18 27]
 [23  3  3 29]
 [ 2 20 27  6]
 [ 9 15  2 30]]
------------------------------------
[[45 59 60 38]
 [59 43 35 56]
 [64 54 45 46]
 [60 44 45 56]
 [58 41 35 55]
 [47 64 42 49]
 [59 61 52 61]
 [57 37 37 63]
 [36 54 61 40]
 [43 49 36 64]]
------------------------------------
[[-23  -9  -8 -30]
 [ -9 -25 -33 -12]
 [ -4 -14 -23 -22]
 [ -8 -24 -23 -12]
 [-10 -27 -33 -13]
 [-21  -4 -26 -19]
 [ -9  -7 -16  -7]
 [-11 -31 -31  -5]
 [-32 -14  -7 -28]
 [-25 -19 -32  -4]]
------------------------------------
[[22 50 52  8]
 [50 18  2 44]
 [60 40 22 24]
 [52 20 22 44]
 [48 14  2 42]
 [26 60 16 30]
 [50 54 36 54]
 [46  6  6 58]
 [ 4 40 54 12]
 [18 30  4 60]]
------------------------------------
[[ 5.5 12.5 13.   2. ]
 [12.5  4.5  0.5 11. ]
 [15.  10.   5.5  6. ]
 [13.   5.   5.5 11. ]
 [12.   3.5  0.5 10.5]
 [ 6.5 15.   4.   7.5]
 [12.5 13.5  9.  13.5]
 [11.5  1.5  1.5 14.5]
 [ 1.  10.  13.5  3. ]
 

In [97]:
a1=np.random.randint(1,12,(2,5))
a2=np.random.randint(34,123,(5,2))
print(a1)
print(a2)
print(a1.dot(a2))

[[ 1  2  5  2  3]
 [ 3  5 11  9  1]]
[[ 93 108]
 [ 88  55]
 [ 90  73]
 [ 63  66]
 [ 82  43]]
[[1091  844]
 [2358 2039]]


**Percentile Function**

In [106]:
np.random.seed(4)
a3=np.random.randint(1,44,10)
print(a3)
a3=np.sort(a3)
print(a3)
# print("000+99((()))"*34)
print(np.percentile(a3,100))

[ 6  2 41 24  9 10 40 31 41 37]
[ 2  6  9 10 24 31 37 40 41 41]
41.0


**Mean,Median,Mode Function**

In [110]:
np.random.seed(4)
a3=np.random.randint(1,44,10)
print(a3.mean())
print(a3.var())
print(a3.std())

24.1
228.09
15.102648774304459


**Filtering Numpy Array**

In [115]:
arr=np.arange(1,50)
print(arr[arr>20])
print(arr[arr<28])

[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


**Transposing the Matrix**

In [118]:
ar2=np.random.randint(1,12,(3,12))
print(ar2)
print("--"*12)
print(ar2.T)

[[10  6  5  3  4  5  8  7  7  9  1  4]
 [ 6  7 11  2  2  7  1 11  9  8  6  8]
 [ 7  9  5  5  1  8  3  2 11  9  9  2]]
------------------------
[[10  6  7]
 [ 6  7  9]
 [ 5 11  5]
 [ 3  2  5]
 [ 4  2  1]
 [ 5  7  8]
 [ 8  1  3]
 [ 7 11  2]
 [ 7  9 11]
 [ 9  8  9]
 [ 1  6  9]
 [ 4  8  2]]


**Where Function**

In [123]:
arr=np.random.randint(1,12,10)
print(arr)
arr1=np.where(arr%2==0,"even",arr)
arr1=np.where(arr%2!=0,"odd",arr1)
print(arr1)

[ 4  7 10  1  4  5  9  7 11  4]
['even' 'odd' 'even' 'odd' 'even' 'odd' 'odd' 'odd' 'odd' 'even']


**Merging Function**

In [130]:
a1=np.random.randint(12,43,(12,2))
a2=np.random.randint(2,23,(12,2))
print(a1)
print(a2)
print(np.concatenate((a1,a2),axis=1))
print('=='*12)
print(np.concatenate((a1,a2),axis=0))
print('--'*12)
print(np.vstack((a1,a2)))
print('--'*12)
print(np.hstack((a1,a2)))

[[25 39]
 [35 36]
 [30 24]
 [36 31]
 [34 41]
 [16 21]
 [39 21]
 [36 26]
 [28 25]
 [22 20]
 [32 13]
 [33 23]]
[[ 5 17]
 [19 20]
 [14  5]
 [13  3]
 [21  7]
 [ 3 22]
 [ 7 15]
 [ 3 16]
 [18  7]
 [21 19]
 [10  2]
 [15 13]]
[[25 39  5 17]
 [35 36 19 20]
 [30 24 14  5]
 [36 31 13  3]
 [34 41 21  7]
 [16 21  3 22]
 [39 21  7 15]
 [36 26  3 16]
 [28 25 18  7]
 [22 20 21 19]
 [32 13 10  2]
 [33 23 15 13]]
[[25 39]
 [35 36]
 [30 24]
 [36 31]
 [34 41]
 [16 21]
 [39 21]
 [36 26]
 [28 25]
 [22 20]
 [32 13]
 [33 23]
 [ 5 17]
 [19 20]
 [14  5]
 [13  3]
 [21  7]
 [ 3 22]
 [ 7 15]
 [ 3 16]
 [18  7]
 [21 19]
 [10  2]
 [15 13]]
------------------------
[[25 39]
 [35 36]
 [30 24]
 [36 31]
 [34 41]
 [16 21]
 [39 21]
 [36 26]
 [28 25]
 [22 20]
 [32 13]
 [33 23]
 [ 5 17]
 [19 20]
 [14  5]
 [13  3]
 [21  7]
 [ 3 22]
 [ 7 15]
 [ 3 16]
 [18  7]
 [21 19]
 [10  2]
 [15 13]]
------------------------
[[25 39  5 17]
 [35 36 19 20]
 [30 24 14  5]
 [36 31 13  3]
 [34 41 21  7]
 [16 21  3 22]
 [39 21  7 15]
 [36 26  3 1

**Splitting the array**

In [134]:
arr=np.random.randint(1,12,(4,4))
print(arr)
print(np.vsplit(arr,4))
print(np.hsplit(arr,4))

[[ 3  2  9  5]
 [ 5  7 10  3]
 [ 1  9  9  2]
 [ 6  7  3  5]]
[array([[3, 2, 9, 5]]), array([[ 5,  7, 10,  3]]), array([[1, 9, 9, 2]]), array([[6, 7, 3, 5]])]
[array([[3],
       [5],
       [1],
       [6]]), array([[2],
       [7],
       [9],
       [7]]), array([[ 9],
       [10],
       [ 9],
       [ 3]]), array([[5],
       [3],
       [2],
       [5]])]


**Turning Pics into numpy arrays**

In [135]:
from matplotlib.image import imread

In [139]:
img=imread("/content/GFG.png")
print(img.shape)
print(img)

(607, 1000, 3)
[[[0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  ...
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]]

 [[0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  ...
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]]

 [[0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  ...
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]
  [0.09803922 0.74509805 0.92941177]]

 ...

 [[0.05882353 0.6039216  0.75686276]
  [0.05882353 0.6039216  0.75686276]
  [0.05882353 0.6039216  0.75686276]
  ...
  [0.05882353 0.6039216  0.75686276]
  [0.05882353 0.6039216  0.75686276]
  [0.05882353 0.6039216  0.75686276]]

 [[0.05882353 0.6039216  0.75686276]
  [0.05882353 0.603921