<a href="https://colab.research.google.com/github/Sardaar2003/Projects/blob/main/Numpy_Practice_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [12]:
ls=[[1,2,3],[4,5,6]]
ls

[[1, 2, 3], [4, 5, 6]]

In [6]:
type(ls)

list

In [13]:
np1=np.array(ls)

In [14]:
np1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
type(np1)

numpy.ndarray

In [16]:
np1.ndim

2

In [18]:
np1.shape

(2, 3)

In [19]:
np1.size

6

In [20]:
np1.dtype

dtype('int64')

In [22]:
zeros=np.zeros((3,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
ones=np.ones((6,3))

In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
arr=np.random.random((4,3))

In [28]:
np.arange(1,10,3)

array([1, 4, 7])

In [31]:
np.linspace(1,10,19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [38]:
arr=np.reshape(arr,(2,6))

In [39]:
arr.flatten()

array([0.40940543, 0.21865597, 0.94377406, 0.06146959, 0.79152411,
       0.94547524, 0.86314575, 0.80262587, 0.31731729, 0.37279529,
       0.21313374, 0.59876359])

In [41]:
arr=[1,2,3,4,5,6]
arr=np.array(arr)

In [50]:
arr=arr**5

In [52]:
arr.max()

7776

In [53]:
arr.min()

1

In [54]:
arr=np.random.random((3,6))

In [55]:
arr

array([[0.20047627, 0.1202747 , 0.29118972, 0.14521447, 0.73808601,
        0.55691296],
       [0.21164313, 0.74706622, 0.44851677, 0.01028954, 0.01555828,
        0.74725984],
       [0.40184632, 0.78898248, 0.86177234, 0.011605  , 0.58662904,
        0.95978622]])

In [56]:
arr.max(axis=1) # Maximum element in the Row wise

array([0.73808601, 0.74725984, 0.95978622])

In [57]:
arr.max(axis=0) # Column Wise Maximum Element

array([0.40184632, 0.78898248, 0.86177234, 0.14521447, 0.73808601,
       0.95978622])

In [58]:
arr.min(axis=1)

array([0.1202747 , 0.01028954, 0.011605  ])

In [59]:
arr.min(axis=0)

array([0.20047627, 0.1202747 , 0.29118972, 0.01028954, 0.01555828,
       0.55691296])

In [60]:
arr.sum()

7.8431093139946855

In [61]:
arr.std()

0.3120621661875186

In [65]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=arr1**3

In [66]:
arr2

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [67]:
arr1*arr2

array([[   1,   16,   81],
       [ 256,  625, 1296],
       [2401, 4096, 6561]])

In [70]:
arr1.dot(arr2)

array([[1158, 1794, 2646],
       [2382, 3729, 5562],
       [3606, 5664, 8478]])

In [71]:
arr2.dot(arr1)

array([[  222,   258,   294],
       [ 2076,  2481,  2886],
       [ 7494,  9078, 10662]])

In [68]:
arr1+arr2

array([[  2,  10,  30],
       [ 68, 130, 222],
       [350, 520, 738]])

In [69]:
arr1-arr2

array([[   0,   -6,  -24],
       [ -60, -120, -210],
       [-336, -504, -720]])

In [72]:
arr=np.arange(1,12,1)

In [80]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr1[:,2:3]

array([[3],
       [6],
       [9]])

In [86]:
arr3=np.array([[7,6,4,5,32,62],[6,8,2,1,5,7],[24,87,43,12,43,2]])

In [92]:
np.sort(arr3,axis=0,kind='quicksort')

array([[ 6,  6,  2,  1,  5,  2],
       [ 7,  8,  4,  5, 32,  7],
       [24, 87, 43, 12, 43, 62]])

In [93]:
arr5=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr6=np.array([[11,12,13,14,15],[6,7,8,9,10],[1,2,3,4,5]])

In [100]:
np.vstack((arr5,arr6))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [97]:
np.hstack((arr5,arr6))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15,  1,  2,  3,  4,  5]])

In [108]:
arr=np.concatenate((arr5,arr6),axis=0)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [109]:
np.vsplit(arr,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[11, 12, 13, 14, 15],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5]])]

In [111]:
arr=np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [113]:
arr2=np.array([12,3,4,5,3,5,454,23,54])

In [114]:
arr2[:-1]

array([ 12,   3,   4,   5,   3,   5, 454,  23])

In [117]:
arr[1:,2:]

array([[7, 8],
       [6, 5],
       [2, 1]])

In [118]:
lst=[1,2,3,4,5,6,7,8,9,10]

In [119]:
lst1=np.array(lst)

In [128]:
lst1[lst1%4==1]

array([1, 5, 9])